/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System.Collections.Generic;
using QuantConnect.Orders;

namespace QuantConnect.Brokerages.Alpaca
{
    /// <summary>
    /// Tracks a single bracket order group consisting of an entry order,
    /// a stop-loss exit leg, and a take-profit exit leg.
    ///
    /// Returned by <see cref="BracketOrderManager.PlaceBracketOrder"/> and
    /// updated internally as order events arrive. The algorithm can query
    /// this object to check bracket state (filled, cancelled, prices, etc.).
    /// </summary>
    public class BracketGroup
    {
        /// <summary>
        /// Unique identifier for this bracket group.
        /// Generated by BracketOrderManager when the bracket is created.
        /// </summary>
        public string GroupId { get; }

        /// <summary>
        /// The symbol being traded in this bracket.
        /// </summary>
        public Symbol Symbol { get; }

        /// <summary>
        /// Signed entry quantity requested. Positive for long brackets, negative for short brackets.
        /// </summary>
        public decimal Quantity { get; }

        /// <summary>
        /// Accumulative signed fill quantity of the entry order so far.
        /// For partial fills this will be less than <see cref="Quantity"/> until fully filled.
        /// In live trading, Alpaca adjusts exit leg quantities to match this value.
        /// </summary>
        public decimal FilledQuantity { get; internal set; }

        /// <summary>
        /// Current stop-loss trigger price. May be updated via UpdateStop().
        /// </summary>
        public decimal StopLossPrice { get; internal set; }

        /// <summary>
        /// Current take-profit limit price. May be updated via UpdateTarget().
        /// </summary>
        public decimal TakeProfitPrice { get; internal set; }

        /// <summary>
        /// Optional stop-limit price for the stop-loss leg.
        /// If set, the stop-loss leg is a stop-limit order rather than a stop-market order.
        /// </summary>
        public decimal? StopLossLimitPrice { get; }

        /// <summary>
        /// Entry order type: Market, Limit, or StopLimit.
        /// </summary>
        public OrderType EntryType { get; }

        /// <summary>
        /// Stop trigger price for stop-limit entry orders. Null for Market/Limit entries.
        /// Updated by UpdateEntry when the entry stop price is changed.
        /// </summary>
        public decimal? EntryStopPrice { get; internal set; }

        // --- Order tickets ---

        /// <summary>
        /// Entry order ticket. Available immediately after PlaceBracketOrder.
        /// </summary>
        public OrderTicket EntryTicket { get; internal set; }

        /// <summary>
        /// Stop-loss leg ticket. Populated by brokerage via RegisterLegTicket
        /// after the entry order fills (backtesting) or after Alpaca responds (live).
        /// </summary>
        public OrderTicket StopTicket { get; internal set; }

        /// <summary>
        /// Take-profit leg ticket. Populated by brokerage via RegisterLegTicket
        /// after the entry order fills (backtesting) or after Alpaca responds (live).
        /// </summary>
        public OrderTicket TargetTicket { get; internal set; }

        // --- State ---

        /// <summary>
        /// True after the entry order has completely filled.
        /// </summary>
        public bool EntryFilled { get; internal set; }

        /// <summary>
        /// True after either exit leg has completely filled.
        /// </summary>
        public bool ExitFilled { get; internal set; }

        /// <summary>
        /// True if the bracket has been cancelled (entry cancelled, or user cancelled).
        /// </summary>
        public bool IsCancelled { get; internal set; }

        /// <summary>
        /// True if the bracket is fully resolved (either an exit filled or the bracket was cancelled).
        /// </summary>
        public bool IsComplete => ExitFilled || IsCancelled;

        /// <summary>
        /// True if this group is a standalone OCO (no entry order).
        /// OCO groups are created by <see cref="BracketOrderManager.RescuePartialFill"/>
        /// with EntryFilled = true and no EntryTicket.
        /// </summary>
        public bool IsOco => EntryFilled && EntryTicket == null;

        /// <summary>
        /// LEAN order IDs of legs currently undergoing an Alpaca replace (update).
        /// Populated by BracketOrderManager when UpdateStop/UpdateTarget is called,
        /// entries removed when the UpdateSubmitted or terminal event arrives.
        /// Used by CancelBracket to avoid cancelling the sibling of a mid-replace leg
        /// (Alpaca rejects sibling cancels during a replace with "pending replacement").
        /// A HashSet supports concurrent updates to both legs (e.g. UpdateStop then
        /// UpdateTarget in rapid succession).
        /// </summary>
        internal readonly HashSet<int> PendingUpdateOrderIds = new();

        /// <summary>
        /// True if CancelBracket was called while the entry order was still in "New"
        /// status (not yet ACK'd by the broker). LEAN rejects cancels on "New" orders,
        /// so the cancel is deferred: ProcessOrderEvent will fire CancelBracket again
        /// when the entry transitions to Submitted (or Filled).
        /// </summary>
        internal bool PendingCancel { get; set; }

        /// <summary>
        /// True if CancelBracket was called at any point before the bracket completed.
        /// Unlike PendingCancel (which is specific to the "New" state race in live trading),
        /// this flag persists even after the entry fills — allowing the backtesting brokerage
        /// to detect and cancel exit legs that were created after a cancel was already requested.
        ///
        /// Scenario: CancelBracket() called on an unfilled limit entry → entry in CancelPending
        /// state → but UpdateEntry resolves first → entry fills on next bar → CreateExitLegs runs.
        /// Without this flag, the exit legs would be orphaned because no cancel was re-attempted.
        /// </summary>
        internal bool CancelRequested { get; set; }

        /// <summary>
        /// Deferred entry update: set when UpdateEntry() is called while the entry order
        /// is still in "New" status (not yet ACK'd by the broker). LEAN rejects updates
        /// on "New" orders, so the update is deferred: ProcessOrderEvent will replay it
        /// when the entry transitions to Submitted. Last-write-wins if called multiple
        /// times before ACK — only the most recent requested price is applied.
        /// </summary>
        internal UpdateOrderFields PendingEntryUpdate { get; set; }

        /// <summary>
        /// Actual entry fill price. Set when the entry order fills.
        /// </summary>
        public decimal? FillPrice { get; internal set; }

        /// <summary>
        /// LEAN order ID of the exit leg that filled. Useful for determining
        /// whether the stop or target triggered.
        /// </summary>
        public int? ExitOrderId { get; internal set; }

        /// <summary>
        /// Actual exit fill price. Set when an exit leg fills.
        /// </summary>
        public decimal? ExitPrice { get; internal set; }

        /// <summary>
        /// Creates a new BracketGroup to track a bracket order.
        /// </summary>
        /// <param name="groupId">Unique identifier for this group.</param>
        /// <param name="symbol">The symbol being traded.</param>
        /// <param name="quantity">Signed quantity (positive=long, negative=short).</param>
        /// <param name="stopLossPrice">Initial stop-loss trigger price.</param>
        /// <param name="takeProfitPrice">Initial take-profit limit price.</param>
        /// <param name="stopLossLimitPrice">Optional stop-limit price for the stop-loss leg.</param>
        /// <param name="entryType">Entry order type (Market, Limit, or StopLimit).</param>
        /// <param name="entryStopPrice">Stop trigger price for stop-limit entries. Null otherwise.</param>
        public BracketGroup(
            string groupId,
            Symbol symbol,
            decimal quantity,
            decimal stopLossPrice,
            decimal takeProfitPrice,
            decimal? stopLossLimitPrice = null,
            OrderType entryType = OrderType.Market,
            decimal? entryStopPrice = null)
        {
            GroupId = groupId;
            Symbol = symbol;
            Quantity = quantity;
            StopLossPrice = stopLossPrice;
            TakeProfitPrice = takeProfitPrice;
            StopLossLimitPrice = stopLossLimitPrice;
            EntryType = entryType;
            EntryStopPrice = entryStopPrice;
        }

        /// <summary>
        /// Returns a human-readable summary of this bracket group's state.
        /// </summary>
        public override string ToString()
        {
            var status = IsComplete
                ? (ExitFilled ? $"ExitFilled(orderId={ExitOrderId}, price={ExitPrice})" : "Cancelled")
                : (EntryFilled ? "Active(entry filled, waiting for exit)" : "Pending(entry not filled)");
            var qtyInfo = FilledQuantity != 0 && FilledQuantity != Quantity
                ? $"qty={FilledQuantity}/{Quantity}" : $"qty={Quantity}";
            var entryInfo = EntryType == OrderType.StopLimit
                ? $"entry=stop-limit(stop={EntryStopPrice})"
                : $"entry={EntryType.ToString().ToLower()}";
            return $"BracketGroup[{GroupId}] {Symbol} {qtyInfo} {entryInfo} stop={StopLossPrice} target={TakeProfitPrice} status={status}";
        }
    }
}
