/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System;

namespace QuantConnect.Brokerages.Alpaca
{
    /// <summary>
    /// Generates semantically meaningful client order IDs for Alpaca orders.
    /// Format: {purpose}-{groupId8}-{leg}-{seq}-{nonce6}
    /// Example: brk-a1b2c3d4-e-0-f9e8d7
    ///
    /// Purpose prefixes:
    ///   brk = bracket entry order
    ///   oco = OCO order (standalone, e.g. emergency OCO)
    ///   rco = rescue OCO (partial fill rescue)
    ///   std = standalone order (non-bracket)
    ///   l2  = Layer 2 replacement protective order
    /// </summary>
    internal static class ClientOrderIdGenerator
    {
        /// <summary>Generate client order ID for a bracket entry order.</summary>
        public static string ForBracketEntry(string groupId)
            => Build("brk", groupId, "e", 0);

        /// <summary>Generate client order ID for an OCO order leg (non-rescue).</summary>
        public static string ForOcoLeg(string groupId, BracketLegType legType)
            => Build("oco", groupId, LegChar(legType), 0);

        /// <summary>Generate client order ID for a rescue OCO order (partial fill rescue).</summary>
        public static string ForRescueOco(string groupId, BracketLegType legType)
            => Build("rco", groupId, LegChar(legType), 0);

        /// <summary>Generate client order ID for a Layer 2 replacement protective order.</summary>
        public static string ForLayer2(string groupId, BracketLegType legType, int seq)
            => Build("l2", groupId, LegChar(legType), seq);

        /// <summary>Generate client order ID for a standalone (non-bracket) order.</summary>
        public static string ForStandalone()
            => Build("std", Guid.NewGuid().ToString("N")[..8], "e", 0);

        /// <summary>
        /// Parse a client order ID back into its semantic components.
        /// Returns null if the string is not in the expected format.
        /// </summary>
        public static ClientOrderIdComponents? Parse(string clientOrderId)
        {
            if (string.IsNullOrEmpty(clientOrderId))
            {
                return null;
            }

            var parts = clientOrderId.Split('-');

            // Format: purpose-groupId8-leg-seq-nonce6 = 5 segments
            if (parts.Length != 5)
            {
                return null;
            }

            if (!int.TryParse(parts[3], out var seq))
            {
                return null;
            }

            var purpose = parts[0];
            if (purpose != "brk" && purpose != "oco" && purpose != "rco" &&
                purpose != "std" && purpose != "l2")
            {
                return null;
            }

            return new ClientOrderIdComponents
            {
                Purpose = purpose,
                GroupPrefix = parts[1],
                Leg = parts[2],
                Seq = seq,
                Nonce = parts[4],
            };
        }

        private static string Build(string purpose, string groupId, string leg, int seq)
        {
            var g8 = groupId.Length >= 8 ? groupId[..8] : groupId.PadRight(8, '0');
            var nonce = Guid.NewGuid().ToString("N")[..6];
            return $"{purpose}-{g8}-{leg}-{seq}-{nonce}";
        }

        private static string LegChar(BracketLegType legType)
            => legType == BracketLegType.TakeProfit ? "t" : "s";
    }

    /// <summary>
    /// Parsed components of a client order ID generated by <see cref="ClientOrderIdGenerator"/>.
    /// </summary>
    internal struct ClientOrderIdComponents
    {
        /// <summary>Order purpose: brk, oco, rco, std, or l2.</summary>
        public string Purpose;

        /// <summary>First 8 characters of the bracket group ID.</summary>
        public string GroupPrefix;

        /// <summary>Leg type: e (entry), s (stop), or t (target).</summary>
        public string Leg;

        /// <summary>Sequence number for replacement orders (0 for initial).</summary>
        public int Seq;

        /// <summary>Random 6-char hex nonce for collision avoidance.</summary>
        public string Nonce;
    }
}
